services:
  app:
    image: apppang2:latest

    container_name: apppang2

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    env_file:
      - .env

    restart: unless-stopped