services:
  mysql:
    image: mysql:8.4

    container_name: apppang-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: apppang
      MYSQL_USER: apppang
      MYSQL_PASSWORD: 1234

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: