spring:
  application:
    name: apppang
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_MAIL_USERNAME}
    password: ${GOOGLE_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    include: secret

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 12MB

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:dummy}
    access-key: ${AWS_ACCESS_KEY_ID:dummy}
    secret-key: ${AWS_SECRET_ACCESS_KEY:dummy}